resilience4j:
  circuitbreaker:
    instances:
      getConsumerGroups:
        slidingWindowType: COUNT_BASED             # Monitor a fixed number of calls
        slidingWindowSize: 10                      # Evaluate the last 50 calls
        failureRateThreshold: 20                   # Open circuit when 50% of calls fail
        minimumNumberOfCalls: 1                   # Start evaluating after at least 10 calls
        waitDurationInOpenState: 120s               # Circuit stays open for 30 seconds
        recordExceptions:
          - java.util.concurrent.TimeoutException  # Record only TimeoutException
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Automatically transition back to HALF_OPEN after wait time
        ignoreExceptions:
          - java.lang.IllegalArgumentException     # Ignore some exceptions if needed
          - org.springframework.web.client.HttpClientErrorException # Ig